<a href="https://colab.research.google.com/github/baxodirmamatvaliev-del/ai_faundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip inistall pandas

ERROR: unknown command "inistall" - maybe you meant "install"

In [ ]:
import pandas as pd

In [ ]:

mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, 8, 1, 9, 3]
}

In [ ]:
df =pd.DataFrame(mydataset)
print("number",df)

number       cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [ ]:
df.head()  # default boshidan  5 ta korsatadi

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [ ]:
df.tail() # default oxiridan boshlab 5 korsatadi

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [ ]:
df.shape

(7, 2)

In [ ]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [ ]:
df.dtypes

cars      object
counts     int64
dtype: object

In [ ]:
import pandas as pd

mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)

print(df.iloc[0])

cars      BMW
counts      3
Name: 0, dtype: object

In [ ]:
df.loc[2:5, "cars"]

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [ ]:
df[df["cars"]== "Tesla"]

    cars  counts
3  Tesla       8

In [ ]:
df["counts"].mean()

np.float64(4.714285714285714)

In [ ]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [ ]:
df.min()

cars      BMW
counts      1
dtype: object

In [ ]:
df.max()

cars      Volvo
counts        9
dtype: object

In [ ]:
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [ ]:
df.count()

cars      7
counts    7
dtype: int64

In [ ]:
df.std(numeric_only=True)

counts    3.199702
dtype: float64

In [ ]:
data_with_missing= {
    "cars": ["BMW", "MUSTANG", None, "TESLA", None, "Ferrari", "Ford"],
    "counts": [1, None, 4, 6, 6, 7 ,9]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     1.0
1  MUSTANG     NaN
2     None     4.0
3    TESLA     6.0
4     None     6.0
5  Ferrari     7.0
6     Ford     9.0

In [ ]:
df_missing.isnull().sum()

cars      2
counts    1
dtype: int64

In [ ]:
df_missing.dropna(subset=["cars"])

      cars  counts
0      BMW     1.0
1  MUSTANG     NaN
3    TESLA     6.0
5  Ferrari     7.0
6     Ford     9.0

In [ ]:
df_missing.fillna('X')

      cars counts
0      BMW    1.0
1  MUSTANG      X
2        X    4.0
3    TESLA    6.0
4        X    6.0
5  Ferrari    7.0
6     Ford    9.0

In [3]:

import pandas as pd

df = pd.read_csv("Titanic-Dataset (1).csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.to_excel("output.xlsx")

In [6]:
# seriec 1D
cars = pd.Series(["BMW", "TESLA", "MUSTANG"])
print(cars)

0        BMW
1      TESLA
2    MUSTANG
dtype: object

In [10]:

import pandas as pd

data_with_missing = pd.DataFrame({
    'cars': ['BMW', 'MUSTANG', None, 'TESLA', None, 'Ferrari', 'Ford'],
    'counts': [1, None, 4, 6, 6, 7, 9]
})

cars_series = data_with_missing['cars']
print(cars_series)

0        BMW
1    MUSTANG
2       None
3      TESLA
4       None
5    Ferrari
6       Ford
Name: cars, dtype: object